const data = {
  products: [
    {
      _id: '1',
      name: 'Personal Private Journal',
      slug: 'personal-private-journal',
      category: 'Personal',
      image: '/images/p5.jpg',
      price: 80,
      countInStock: 10,
      brand: 'YPA',
      rating: 4.5,
      numReviews: 10,
      description: 'Made with LOVE!',
    },

    {
      _id: '2',
      name: 'Fruit Theme Journal',
      slug: 'fruit-theme-journal',
      category: 'Fruit Theme',
      image: '/images/p6.jpg',
      price: 100,
      countInStock: 10,
      brand: 'YPA',
      rating: 4.0,
      numReviews: 10,
      description: 'Made with LOVE!',
    },

    {
      _id: '3',
      name: 'Flower Theme Journal',
      slug: 'flower-theme-journal',
      category: 'Flower Theme',
      image: '/images/p7.jpg',
      price: 90,
      countInStock: 15,
      brand: 'YPA',
      rating: 4.5,
      numReviews: 14,
      description: 'Made with LOVE!',
    },

    // {
    //   _id: '3',
    //   name: 'Nike Fit Pant',
    //   slug: 'nike-fit-pant',
    //   category: 'Pants',
    //   image: '/images/p7.jpg',
    //   price: 20,
    //   countInStock: 15,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 14,
    //   description: 'high quality product',
    // },

    {
      _id: '4',
      name: 'Passport Type Journal',
      slug: 'passport-type-journal',
      category: 'Passport',
      image: '/images/p8.jpg',
      price: 60,
      countInStock: 0,
      brand: 'YPA',
      rating: 4.5,
      numReviews: 10,
      description: 'Made with LOVE!',
    },

    // {
    //   _id: '4',
    //   name: 'Addidas Fit Pant',
    //   slug: 'addidas-fit-pant',
    //   category: 'Pants',
    //   image: '/images/p8.jpg',
    //   price: 60,
    //   countInStock: 0,
    //   brand: 'Addidas',
    //   rating: 4.5,
    //   numReviews: 10,
    //   description: 'high quality product',
    // },
  ],
};

export default data;
